<a href="https://colab.research.google.com/github/AnasShafiq/Pandas/blob/main/Python_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hello lets GO !!')

Hello lets GO !!


#Inputs

In [ ]:
number1 = int(input('Input the first Number = :'))
number2 = int(input('Enter the second number'))

Sum = number1 + number2
print(Sum)

Input the first Number = :3
Enter the second number3
6


#IF ELSE Statements


In [ ]:
#Basic IF Else statement
a = int(input('Enter the first Number ='))
b = int(input('Enter the second Number ='))
c = int(input('Enter the third Number ='))
if (a<b):
  print('A is the greater Number')
else:
  print('B is the greater Number')

# IF ELIF ELSE case:


if (b<a>c):
  print('A is the greatest Number')
elif (a<b>c):
  print('B is the greatest Number')
else:
  print('C is the greatest Number')

#Nested IF Statement

if (a>b):
  if (a>c):
    print('A is the greatest number')
  else:
    print('C is the greatest Number')

Enter the first Number =44
Enter the second Number =2
Enter the third Number =31
B is the greater Number
A is the greatest Number
A is the greatest number


# LOOPS

In [ ]:
# for Loop
for i in range(5):
  phone_price = int(input('Enter the price of the phones'))
# another example with list
numbers = [1,2,3,4,5,6,7]
for i in numbers:
  print(i)

# While Loops
a = int(input('Enter the amount you want your message to print for = '))
b = input('Enter the message the you want to print = ')
while a<0 :
  print(b)
  a+=1

Enter the price of the phones4
Enter the price of the phones4
Enter the price of the phones4
Enter the price of the phones4
Enter the price of the phones4
1
2
3
4
5
6
7
Enter the amount you want your message to print for = 10
Enter the message the you want to print = HELLO THERE


In [ ]:
# While Loops
a = int(input('Enter the amount you want your message to print for = '))
b = input('Enter the message the you want to print = ')
while a<=0 :
  print(b)
  a +=1
else:
  print('Input value was less than 0')

Enter the amount you want your message to print for = 5
Enter the message the you want to print = Na
Input value was less than 0


#Functions

In [ ]:

def factorial_value(num):

  factorial = 1

  if num == 0:
    return factorial

  else:
    for i in range(1, num+1):
      factorial = factorial*i
    return factorial


In [ ]:
print(factorial_value(4))

24


#Numpy

In [ ]:
import numpy as np
# Numpy arrays
list1 = np.array([1,2,3,4,5])
type(list1)
#cheking the dimention of the array
list1.shape
#making a 2 dimentional array
a = np.array([[1,2,3,4],[5,6,7,8]])
a.shape
#Initial Placeholders in numpay arrays
x = np.zeros((2,2)) #prints an array of all 0
print(x)
y  = np.ones((3,3)) # prints an array of all 1
print(y)
z = np.full((3,2),2) #prints an array of any specific numbers
print(z)
i = np.eye(4)# prints an identity matrix
print(i)
b = np.random.random ((3,4)) #creats an array of random values between 0 and 1
print(b)
r= np.random.randint(10,1000,(3,4))# creats an array of random integers
print(r)

#Converting lists to np.array
list1 = [1,2,3,4,5,6]
NP = np.asarray(list1)
NP
type(NP)

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.99301261 0.72269646 0.26078971 0.95618511]
 [0.19703816 0.47925657 0.98182354 0.53746392]
 [0.70759729 0.84024567 0.86945072 0.33000192]]
[[ 85 139 426 215]
 [511 334 284  72]
 [447 744 589 348]]


numpy.ndarray

Analysing an array

In [ ]:
arr = np.random.randint(10,99,(5,5))
print(arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)
print(arr.size)


[[19 72 63 70 43]
 [90 13 23 80 19]
 [73 81 80 64 63]
 [60 31 35 63 39]
 [97 79 37 64 97]]
<class 'numpy.ndarray'>
(5, 5)
2
25


Mathematical Operations on an array

In [ ]:
a = np.random.randint(10,100,(3,3))
b = np.random.randint(10,99,(3,3))
print(a)
print(b)
#Simple way
print(a+b)
print(a-b)
print(a/b)
print(a*b)
print(np.add(a,b))
print(np.subtract(a,b))

[[59 93 39]
 [32 68 32]
 [47 28 18]]
[[93 46 79]
 [12 64 10]
 [25 82 66]]
[[152 139 118]
 [ 44 132  42]
 [ 72 110  84]]
[[-34  47 -40]
 [ 20   4  22]
 [ 22 -54 -48]]
[[0.6344086  2.02173913 0.49367089]
 [2.66666667 1.0625     3.2       ]
 [1.88       0.34146341 0.27272727]]
[[5487 4278 3081]
 [ 384 4352  320]
 [1175 2296 1188]]
[[152 139 118]
 [ 44 132  42]
 [ 72 110  84]]
[[-34  47 -40]
 [ 20   4  22]
 [ 22 -54 -48]]


Array Manipulation

In [ ]:
#simple methord
print (a)
at = np.transpose(a)
print(at)
#short Methord
a.T

[[59 93 39]
 [32 68 32]
 [47 28 18]]
[[59 32 47]
 [93 68 28]
 [39 32 18]]


array([[59, 32, 47],
       [93, 68, 28],
       [39, 32, 18]])